# This docker compose file can be used to start up a statemodify notebook locally
# for testing.
services:
  notebook:
    container_name: cerf-notebook
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/msd-live/jupyter/cerf-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./data:/data
      - ./notebooks:/home/jovyan/notebooks
